### ISSUE TITLE
강의 계획서 관련 부분의 새로고침에 실패하는 버그

### ISSUE THREAD

**Issue by tpdns90321** [s-owl/skhu-app#61]

**Comment by tpdns90321** [comment]
<img width="901" alt="스크린샷 2019-06-26 오후 1 26 24" src="https://user-images.githubusercontent.com/10331327/60151014-09a4ab80-9816-11e9-91b3-43b59585ed73.png">

**Comment by sukso96100** [comment]
포레스트상에서 레이아웃 어떻게 나온느지가 중요할듯. 전공제 학부제에 따라 다르게 나오는지부터 봐야함
