### ISSUE TITLE
SAM의 세션이 forest 보다 먼저 끝나는 것 같습니다.

### ISSUE THREAD

**Issue by tpdns90321** [s-owl/skhu-app#84]

**Comment by sukso96100** [comment]
Sam 이 몇분정도 가는거 같음?

**Comment by tpdns90321** [comment]
일단 75분 보다는 짧아요.

**Comment by sukso96100** [comment]
전산소 문의가 젤 빠를 듯 한데 메일 등으로 문의해서 한번 알아봐

**Comment by tpdns90321** [comment]
백그라운드에서 1시간 넘게 있던 앱에서 테스트해보니 특히 강의계획서가 로드가 안되는 것으로 보여요

**Comment by tpdns90321** [comment]
또 특히한게 강의계획서 목록은 잘 뜨고 포레스트 기능은 잘 작동하고

**Comment by sukso96100** [comment]
전자계산소에 문의해서 sam 쪽 세션 유지시간 얼마나 되는지 한번 알아봐. 일단 60분 까지는 유지됨?

**Comment by tpdns90321** [comment]
한 30분 45분 이렇게 테스트해보고 말씀드릴게요

**Comment by tpdns90321** [comment]
우연히 발견한거라

**Comment by sukso96100** [comment]
Ok

**Comment by tpdns90321** [comment]
정확히 60분입니다.

**Comment by sukso96100** [comment]
그럼 일단 60분으로 줄이자

**Comment by tpdns90321** [comment]
ok

**Comment by tpdns90321** [comment]
이참에 로그인 토큰 고치는 김에 백그라운드에 계속 보관하시는 분들을 위해서 다시 로그인하는 방식이 있어야 할 것 같은데요.

**Comment by tpdns90321** [comment]
#85 
일단은 로그인 강의계획서 상세는 해결
이제는 백그라운드에 계속 스쿠즈를 상주시키고 사용하는 사람들한테 제보가 들어왔는데
스쿠즈를 계속 방치하고 있으면 나중에 강의계획서 상세 들어갈 때 똑같은 문제가 발생한다고 합니다.

**Comment by tpdns90321** [comment]
그리고 expo 에서 확인하고 publish 할게요

**Comment by sukso96100** [comment]
Ok

**Comment by sukso96100** [comment]
백그라운드에서 주기적으로 갱신하는거면 이걸 쓰면 될듯
https://docs.expo.io/versions/latest/sdk/background-fetch/

**Comment by sukso96100** [comment]
백그라운드 세션 갱신은 앱쪽서 처리해야 하니 별도 이슈로 열자

**Comment by tpdns90321** [comment]
ㅇㅇ
