### ISSUE TITLE
백그라운드에서 세션 갱신

### ISSUE THREAD

**Issue by sukso96100** [s-owl/skhu-app#89]
앱을 명시적으로 끈 것이 아닌 다른 앱으로 전환 했다가 장시간 후 다시 돌아와도 이용에 이상이 없도록, 앱을 켠 후 백그라운드에서 일정 시간마다 주기적으로 세션 데이터를 갱신하도록 앱을 수정.

2가지 정도 구현 방법이 있음.
- MainShell 진입 시 `setInterval()` 호출하여 구현
- Expo 의 BackgroundFetch 를 이용하여 구현(권한 조절이 필요하며, 스토어 통한 업데이트 필요함)

**Comment by tpdns90321** [comment]
3. 오류 발생 시 로그인 시도
이렇게 변경했고 완성했습니다.

**Comment by sukso96100** [comment]
굳 슬슬 PR 여셈

**Comment by tpdns90321** [comment]
PR 열고 마스터에 한번하고 교원시간표에 수정사항 있습니다. 이제 postToSam과 getFromSam의 출력값이 async null 혹은 async json 변경해야합니다.

**Comment by sukso96100** [comment]
[ ] hotfix/timeout -> master 로 병합
[ ] master -> develop 으로 병합
[ ] develop, feature/professor-timetable 충돌 수정 및 병합

**Comment by tpdns90321** [comment]
마지막으로 점검하고 master에 병합합니다.

**Comment by sukso96100** [comment]
ㅇㅋ

**Comment by tpdns90321** [comment]
#99 이걸 테스트 못했네

**Comment by tpdns90321** [comment]
이제 이것도 끝난 것 같네요
